/* eslint-disable react-hooks/rules-of-hooks */
import {useId} from 'react'
// WINTER
import Wdata_1 from '../assets/Winter_Collections/winter_Evening garden.jpg'
import Wdata_2 from '../assets/Winter_Collections/Winter_Lavender-roses.jpg'
import Wdata_3 from '../assets/Winter_Collections/Winter_Tropical-leaves.jpg'
import Wdata_4 from '../assets/Winter_Collections/winter_Alpari.jpg'
import Wdata_5 from '../assets/Winter_Collections/winter_Arabesque.jpg'
import Wdata_6 from '../assets/Winter_Collections/winter_Bambi.jpg'
import Wdata_7 from '../assets/Winter_Collections/winter_Black and white robe.jpg'
import Wdata_8 from '../assets/Winter_Collections/winter_Byzantium.jpg'
import Wdata_9 from '../assets/Winter_Collections/winter_Cherry blossom.jpg'
import Wdata_10 from '../assets/Winter_Collections/winter_Circles.jpg'
import Wdata_11 from '../assets/Winter_Collections/winter_Disney.jpg'
import Wdata_12 from '../assets/Winter_Collections/winter_Eco loft.jpg'
import Wdata_13 from '../assets/Winter_Collections/winter_Evening garden.jpg'
import Wdata_14 from '../assets/Winter_Collections/winter_Feather Marquis.jpg'
import Wdata_15 from '../assets/Winter_Collections/winter_Funny bears.jpg'
import Wdata_16 from '../assets/Winter_Collections/winter_Geometry blue.jpg'
import Wdata_17 from '../assets/Winter_Collections/winter_Harmony.jpg'
import Wdata_18 from '../assets/Winter_Collections/winter_Ikat.jpg'
import Wdata_19 from '../assets/Winter_Collections/winter_Lavender roses.jpg'
import Wdata_20 from '../assets/Winter_Collections/winter_Luxury.jpg'
import Wdata_21 from '../assets/Winter_Collections/winter_Moon Scorpio.jpg'
import Wdata_22 from '../assets/Winter_Collections/winter_Sapphire shine.jpg'
import Wdata_23 from '../assets/Winter_Collections/winter_Spectrum.jpg'
import Wdata_24 from '../assets/Winter_Collections/winter_Squares.jpg'
import Wdata_25 from '../assets/Winter_Collections/winter_Vasilisa.jpg'

// SUMMER
import Sdata_1 from "../assets/Summer_collections/Child's world.jpg"
import Sdata_2 from "../assets/Summer_collections/Dastarkhan.jpg"
import Sdata_3 from "../assets/Summer_collections/Delicate tulip.jpg"
import Sdata_4 from "../assets/Summer_collections/Dolly the Sheep.jpg"
import Sdata_5 from "../assets/Summer_collections/Field chamomile.jpg"
import Sdata_6 from "../assets/Summer_collections/French Riviera.jpg"
import Sdata_7 from "../assets/Summer_collections/Golden meander.jpg"
import Sdata_8 from "../assets/Summer_collections/Green lotus.jpg"
import Sdata_9 from "../assets/Summer_collections/Highway.jpg"
import Sdata_10 from "../assets/Summer_collections/Mountain cornflower.jpg"
import Sdata_11 from "../assets/Summer_collections/Olive branch.jpg"
import Sdata_12 from "../assets/Summer_collections/Peasant woman.jpg"
import Sdata_13 from "../assets/Summer_collections/Singing Calibri.jpg"
import Sdata_14 from "../assets/Summer_collections/Sirius.jpg"
import Sdata_15 from "../assets/Summer_collections/fluttering dandelion.jpg"
import Sdata_16 from "../assets/Summer_collections/sum_Alpine herbs.jpg"
import Sdata_17 from "../assets/Summer_collections/sum_Dolly-the-Sheep.jpg"
import Sdata_18 from "../assets/Summer_collections/sum_French Riviera.jpg"
import Sdata_19 from "../assets/Summer_collections/sum_Sakura branch.jpg"
import Sdata_20 from "../assets/Summer_collections/sum_Inspirational.jpg"
import Sdata_21 from "../assets/Summer_collections/sum_Vintage style.jpg"
import Sdata_22 from "../assets/Summer_collections/summer_Butterfly.jpg"
import Sdata_23 from "../assets/Summer_collections/summer_climbing buttercup.jpg"
import Sdata_24 from "../assets/Summer_collections/winter_Boomerang.jpg"
import Sdata_25 from "../assets/Summer_collections/winter_East Damascus.jpg"
import Sdata_26 from "../assets/Summer_collections/winter_Versailles A.jpg"
import Sdata_27 from "../assets/Summer_collections/winter_Versailles B.jpg"

// AUTUMN
import Adata_1 from "../assets/Automn_Collections/Aquamarine.jpg"
import Adata_2 from "../assets/Automn_Collections/Asian fern.jpg"
import Adata_3 from "../assets/Automn_Collections/Autumn leaf fall (AB).jpg"
import Adata_4 from "../assets/Automn_Collections/Babylon.jpg"
import Adata_5 from "../assets/Automn_Collections/Bay sprig A.jpg"
import Adata_6 from "../assets/Automn_Collections/Bay sprig B.jpg"
import Adata_7 from "../assets/Automn_Collections/Blooming Cattleya.jpg"
import Adata_8 from "../assets/Automn_Collections/Blue Breeze (AB).jpg"
import Adata_9 from "../assets/Automn_Collections/Burberry.jpg"
import Adata_10 from "../assets/Automn_Collections/Delicate tartan.jpg"
import Adata_11 from "../assets/Automn_Collections/Emerald (AB).jpg"
import Adata_13 from "../assets/Automn_Collections/Forest chamomile.jpg"
import Adata_14 from "../assets/Automn_Collections/Fortune.jpg"
import Adata_15 from "../assets/Automn_Collections/Imperial.jpg"
import Adata_16 from "../assets/Automn_Collections/Konopelka.jpg"
import Adata_17 from "../assets/Automn_Collections/Lilac mimulus.jpg"
import Adata_18 from "../assets/Automn_Collections/Malachite Box.jpg"
import Adata_19 from "../assets/Automn_Collections/Multicolored amethyst.jpg"
import Adata_20 from "../assets/Automn_Collections/Palm leaf.jpg"
import Adata_21 from "../assets/Automn_Collections/Plaid.jpg"
import Adata_22 from "../assets/Automn_Collections/Safari.jpg"
import Adata_23 from "../assets/Automn_Collections/Scents of spring.jpg"
import Adata_24 from "../assets/Automn_Collections/aut_Stucco-ornament.jpg"
import Adata_25 from "../assets/Automn_Collections/Symphony A.jpg"
import Adata_26 from "../assets/Automn_Collections/Symphony B.jpg"
import Adata_27 from "../assets/Automn_Collections/Valerian.jpg"
import Adata_28 from "../assets/Automn_Collections/Water Blue (AB).jpg"
import Adata_29 from "../assets/Automn_Collections/Wild Orchid.jpg"




    
export const Data = [
        {
            id: 1,
            image: Wdata_1,
            name: "Evening garden",
            category:"Winter collection",
            general: true,
            sort_ppopular: false,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: false,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 2,
            image: Wdata_2,
            name: "Lavender roses",
            category:"Winter collection",
            general: true,
            sort_ppopular: false,
            sort_rating: true,
            sort_novelty: false,
            sort_price_ascending: true,
            sort_price_descending: false,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 0,
            image: Wdata_3,
            name: "Tropical leaves",
            category:"Winter collection",
            general: true,
            sort_ppopular: false,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: false,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 3,
            image: Wdata_4,
            name: "winter Alpari",
            category:"Winter collection",
            general: true,
            sort_ppopular: false,
            sort_rating: true,
            sort_novelty: false,
            sort_price_ascending: false,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 4,
            image: Wdata_5,
            name: "winter Arabesque",
            category:"Winter collection",
            general: true,
            sort_ppopular: false,
            sort_rating: true,
            sort_novelty: false,
            sort_price_ascending: true,
            sort_price_descending: false,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 5,
            image: Wdata_6,
            name: "winter Bambi",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 6,
            image: Wdata_7,
            name: "Black and white robe",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 7,
            image: Wdata_8,
            name: "Byzantium",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id:8,
            image: Wdata_9,
            name: "Cherry blossom",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 9,
            image: Wdata_10,
            name: "Circles",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 10,
            image: Wdata_11,
            name: "Disney",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 11,
            image: Wdata_12,
            name: "Eco loft",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 12,
            image: Wdata_13,
            name: "Evening garden",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 13,
            image: Wdata_14,
            name: "Feather Marquis",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 14,
            image: Wdata_15,
            name: "Funny bears",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 15,
            image: Wdata_16,
            name: "Geometry blue",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 1,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 16,
            image: Wdata_17,
            name: "Harmony",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 17,
            image: Wdata_18,
            name: "Ikat",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 18,
            image: Wdata_19,
            name: "Lavender roses",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 19,
            image: Wdata_20,
            name: "Luxury",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 20,
            image: Wdata_21,
            name: "Moon Scorpio",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 21,
            image: Wdata_22,
            name: "Sapphire shine",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 22,
            image: Wdata_23,
            name: "Spectrum",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 23,
            image: Wdata_24,
            name: "Squares",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 24,
            image: Wdata_25,
            name: "Vasilisa",
            category:"Winter collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },


        {
            id: 25,
            image: Sdata_1,
            name: "Child's world",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 26,
            image: Sdata_2,
            name: "Dastarkhan",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 27,
            image: Sdata_3,
            name: "Delicate tulip",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 28,
            image: Sdata_4,
            name: "Dolly the Sheep",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 29,
            image: Sdata_5,
            name: "Field chamomile",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 30,
            image: Sdata_6,
            name: "French Riviera",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 31,
            image: Sdata_7,
            name: "Golden meander",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 2,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id:32,
            image: Sdata_8,
            name: "Green lotus",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 33,
            image: Sdata_9,
            name: "Highway",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 34,
            image: Sdata_10,
            name: "Mountain cornflower",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 35,
            image: Sdata_11,
            name: "Olive branch",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 36,
            image: Sdata_12,
            name: "Peasant woman",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 37,
            image: Sdata_13,
            name: "Singing Calibri",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 38,
            image: Sdata_14,
            name: "Sirius",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 39,
            image: Sdata_15,
            name: "fluttering dandelion",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 40,
            image: Sdata_16,
            name: "Alpine herbs",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 41,
            image: Sdata_17,
            name: "Dolly-the-Sheep",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 42,
            image: Sdata_18,
            name: "French Riviera",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 43,
            image: Sdata_19,
            name: "Sakura branch",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 44,
            image: Sdata_20,
            name: "Inspirational",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 45,
            image: Sdata_21,
            name: "Vintage style",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 46,
            image: Sdata_22,
            name: "Butterfly",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 47,
            image: Sdata_23,
            name: "climbing buttercup",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 3,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 48,
            image: Sdata_24,
            name: "winter_Boomerang",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 49,
            image: Sdata_25,
            name: "East Damascus",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 49,
            image: Sdata_26,
            name: "Versailles A",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 50,
            image: Sdata_27,
            name: "Versailles B",
            category:"Summer collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },


        {
            id: 51,
            image: Adata_1,
            name: "Aquamarine",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 52,
            image: Adata_2,
            name: "Asian fern",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 53,
            image: Adata_3,
            name: "Autumn leaf fall (AB)",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 54,
            image: Adata_4,
            name: "Babylon",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 55,
            image: Adata_5,
            name: "Bay sprig A",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 56,
            image: Adata_6,
            name: "Bay sprig B",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 57,
            image: Adata_7,
            name: "Blooming Cattleya",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 58,
            image: Adata_8,
            name: "Blue Breeze (AB)",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 59,
            image: Adata_9,
            name: "Burberry",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 60,
            image: Adata_10,
            name: "Delicate tartan",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 61,
            image: Adata_11,
            name: "Emerald (AB)",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 62,
            image: Adata_13,
            name: "Forest chamomile",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 4,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 63,
            image: Adata_14,
            name: "Fortune",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 64,
            image: Adata_15,
            name: "Imperial",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 65,
            image: Adata_16,
            name: "Konopelka",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 1,
            main_page: 55,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 66,
            image: Adata_17,
            name: "Lilac mimulus",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 67,
            image: Adata_18,
            name: "Malachite Box",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 68,
            image: Adata_19,
            name: "Multicolored amethyst",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 69,
            image: Adata_20,
            name: "Palm leaf",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 70,
            image: Adata_21,
            name: "Plaid",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 80,
            image: Adata_22,
            name: "Safari",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 81,
            image: Adata_23,
            name: "Scents of spring",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 82,
            image: Adata_24,
            name: "Stucco-ornament",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 83,
            image: Adata_25,
            name: "Symphony A",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 84,
            image: Adata_26,
            name: "Symphony B",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 85,
            image: Adata_27,
            name: "Valerian",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 86,
            image: Adata_28,
            name: "Water Blue (AB)",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
        {
            id: 87,
            image: Adata_29,
            name: "Wild Orchid",
            category:"Autumn collection",
            general: true,
            sort_ppopular: true,
            sort_rating: true,
            sort_novelty: true,
            sort_price_ascending: true,
            sort_price_descending: true,
            page: 2,
            main_page: 5,
            Material: "100% cotton flannel",
            Pillowcase: "50x70 cm (2 pcs.)",
            Bed_sheet: "260x280 cm (1 piece)",
            Duvet_cover: "160x220 cm (2 pcs.)",
            Size: "Special size",
            Manufacturer: "Bukhara Natural Product"
        },
    ]
 
 

  